# Generated by Django 5.2.5 on 2026-01-25 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstanding_debt', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('delay_from_due_date', models.IntegerField()),
                ('credit_history_months', models.IntegerField()),
                ('credit_mix', models.IntegerField()),
                ('changed_credit_limit', models.FloatField()),
                ('num_credit_inquiries', models.IntegerField()),
                ('payment_of_min_amount', models.IntegerField()),
                ('num_bank_accounts', models.IntegerField()),
                ('monthly_balance', models.FloatField()),
                ('annual_income', models.FloatField()),
                ('total_emi_per_month', models.FloatField()),
                ('predicted_category', models.CharField(choices=[('good', 'Good'), ('standard', 'Standard'), ('poor', 'Poor')], max_length=10)),
                ('credit_score', models.IntegerField()),
                ('prob_good', models.FloatField()),
                ('prob_poor', models.FloatField()),
                ('prob_standard', models.FloatField()),
                ('ai_explanation', models.TextField(blank=True, null=True)),
                ('shap_plot', models.ImageField(blank=True, null=True, upload_to='shap_plots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prediction Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
