# Generated by Django 5.2.5 on 2026-01-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditscore',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Credit Scores'},
        ),
    ]
